import os
from typing import List, Dict

# Default configuration
DEFAULT_CONFIG = {
    "model": "gpt-5-mini",
    "available_models": ["gpt-5-mini", "gpt-4o-mini", "gpt-4o", "gpt-4-turbo", "gpt-3.5-turbo"],
    "batch_size": 10,
    "rate_limit": 1.2,
    "max_retries": 3,
    "supported_languages": {
        # Common languages
        "en": "English",
        "es": "Spanish",
        "fr": "French",
        "de": "German",
        "it": "Italian",
        "pt": "Portuguese",
        "ru": "Russian",
        "zh": "Chinese",
        "ja": "Japanese",
        "ko": "Korean",
        "ar": "Arabic",
        "hi": "Hindi",
        "tr": "Turkish",
        "nl": "Dutch",
        "pl": "Polish",
        "vi": "Vietnamese",
        "th": "Thai",
        "id": "Indonesian",
        "ms": "Malay",
        "fa": "Persian",
        "he": "Hebrew",
        "da": "Danish",
        "fi": "Finnish",
        "no": "Norwegian",
        "sv": "Swedish",
        "cs": "Czech",
        "hu": "Hungarian",
        "ro": "Romanian",
        "el": "Greek",
        "bg": "Bulgarian",
        "hr": "Croatian",
        "sk": "Slovak",
        "sl": "Slovenian",
        "et": "Estonian",
        "lv": "Latvian",
        "lt": "Lithuanian",
        "uk": "Ukrainian",
        "be": "Belarusian",
        "sr": "Serbian",
        "bs": "Bosnian",
        "mk": "Macedonian",
        "az": "Azerbaijani",
        "ka": "Georgian",
        "hy": "Armenian",
        "uz": "Uzbek",
        "kk": "Kazakh",
        "ky": "Kyrgyz",
        "tg": "Tajik",
        "mn": "Mongolian",
        "ne": "Nepali",
        "si": "Sinhala",
        "ta": "Tamil",
        "te": "Telugu",
        "kn": "Kannada",
        "ml": "Malayalam",
        "bn": "Bengali",
        "gu": "Gujarati",
        "mr": "Marathi",
        "pa": "Punjabi",
        "ur": "Urdu",
        "fa": "Persian",
        "ps": "Pashto",
        "ku": "Kurdish",
        "sd": "Sindhi",
        "lo": "Lao",
        "km": "Khmer",
        "my": "Burmese",
        "am": "Amharic",
        "ti": "Tigrinya",
        "so": "Somali",
        "sw": "Swahili",
        "yo": "Yoruba",
        "ha": "Hausa",
        "ig": "Igbo",
        "zu": "Zulu",
        "xh": "Xhosa",
        "st": "Sesotho",
        "sn": "Shona",
        "ny": "Chichewa",
        "mg": "Malagasy",
        "rw": "Kinyarwanda",
        "ceb": "Cebuano",
        "hmn": "Hmong",
        "haw": "Hawaiian",
        "sm": "Samoan",
        "to": "Tongan",
        "fj": "Fijian",
        "mi": "Maori",
        "ty": "Tahitian",
        "co": "Corsican",
        "fy": "Frisian",
        "gd": "Scottish Gaelic",
        "cy": "Welsh",
        "ga": "Irish",
        "mt": "Maltese",
        "is": "Icelandic",
        "fo": "Faroese",
        "gl": "Galician",
        "eu": "Basque",
        "ca": "Catalan",
        "ast": "Asturian",
        "oc": "Occitan",
        "sc": "Sardinian",
        "vec": "Venetian",
        "nap": "Neapolitan",
        "scn": "Sicilian",
        "pms": "Piedmontese",
        "lij": "Ligurian",
        "lmo": "Lombard",
        "eml": "Emilian",
        "fur": "Friulian",
        "lld": "Ladin",
        "rm": "Romansh",
        "wa": "Walloon",
        "pcd": "Picard",
        "gsw": "Swiss German",
        "als": "Alemannic",
        "bar": "Bavarian",
        "ksh": "Colognian",
        "lb": "Luxembourgish",
        "li": "Limburgish",
        "vls": "West Flemish",
        "zea": "Zeelandic",
        "af": "Afrikaans",
        "an": "Aragonese",
        "ang": "Old English",
        "arc": "Aramaic",
        "arn": "Mapuche",
        "av": "Avar",
        "ay": "Aymara",
        "ba": "Bashkir",
        "bh": "Bihari",
        "bi": "Bislama",
        "bo": "Tibetan",
        "br": "Breton",
        "bug": "Buginese",
        "byn": "Blin",
        "chr": "Cherokee",
        "chv": "Chuvash",
        "crh": "Crimean Tatar",
        "csb": "Kashubian",
        "cv": "Chuvash",
        "dv": "Divehi",
        "dz": "Dzongkha",
        "ee": "Ewe",
        "ff": "Fula",
        "fil": "Filipino",
        "frm": "Middle French",
        "frr": "Northern Frisian",
        "frp": "Arpitan",
        "frv": "Franco-Provençal",
        "fur": "Friulian",
        "gag": "Gagauz",
        "gan": "Gan Chinese",
        "glk": "Gilaki",
        "gn": "Guaraní",
        "gom": "Goan Konkani",
        "gor": "Gorontalo",
        "got": "Gothic",
        "grc": "Ancient Greek",
        "gsw": "Swiss German",
        "hak": "Hakka Chinese",
        "hif": "Fiji Hindi",
        "ho": "Hiri Motu",
        "hsb": "Upper Sorbian",
        "hsn": "Xiang Chinese",
        "ht": "Haitian Creole",
        "hz": "Herero",
        "ia": "Interlingua",
        "ie": "Interlingue",
        "ik": "Inupiaq",
        "ilo": "Iloko",
        "inh": "Ingush",
        "io": "Ido",
        "jbo": "Lojban",
        "jv": "Javanese",
        "kab": "Kabyle",
        "kbd": "Kabardian",
        "kbp": "Kabiye",
        "kg": "Kongo",
        "ki": "Kikuyu",
        "kj": "Kuanyama",
        "kk": "Kazakh",
        "kl": "Kalaallisut",
        "kmb": "Kimbundu",
        "kr": "Kanuri",
        "krc": "Karachay-Balkar",
        "kri": "Krio",
        "krj": "Kinaray-a",
        "ks": "Kashmiri",
        "ksh": "Colognian",
        "kum": "Kumyk",
        "kv": "Komi",
        "kw": "Cornish",
        "lad": "Ladino",
        "lbe": "Lak",
        "lez": "Lezghian",
        "lg": "Ganda",
        "lrc": "Northern Luri",
        "ltg": "Latgalian",
        "lzh": "Literary Chinese",
        "mdf": "Moksha",
        "mh": "Marshallese",
        "mhr": "Eastern Mari",
        "mi": "Maori",
        "min": "Minangkabau",
        "mk": "Macedonian",
        "mn": "Mongolian",
        "mni": "Manipuri",
        "moh": "Mohawk",
        "mrj": "Western Mari",
        "ms": "Malay",
        "mwl": "Mirandese",
        "myv": "Erzya",
        "mzn": "Mazanderani",
        "na": "Nauru",
        "nan": "Min Nan Chinese",
        "nap": "Neapolitan",
        "nds": "Low German",
        "new": "Newari",
        "nia": "Nias",
        "niu": "Niuean",
        "nqo": "N'Ko",
        "nso": "Northern Sotho",
        "nv": "Navajo",
        "ny": "Chichewa",
        "nys": "Nyungar",
        "olo": "Livvi-Karelian",
        "om": "Oromo",
        "or": "Odia",
        "os": "Ossetian",
        "pag": "Pangasinan",
        "pam": "Pampanga",
        "pap": "Papiamento",
        "pcd": "Picard",
        "pdc": "Pennsylvania German",
        "pfl": "Palatine German",
        "pms": "Piedmontese",
        "pnt": "Pontic",
        "prg": "Prussian",
        "qu": "Quechua",
        "quc": "K'iche'",
        "qug": "Chimborazo Highland Quichua",
        "rgn": "Romagnol",
        "rif": "Riffian",
        "rm": "Romansh",
        "rn": "Rundi",
        "roa-rup": "Aromanian",
        "roa-tara": "Tarantino",
        "rue": "Rusyn",
        "rup": "Aromanian",
        "sah": "Yakut",
        "sat": "Santali",
        "sc": "Sardinian",
        "scn": "Sicilian",
        "sco": "Scots",
        "sdh": "Southern Kurdish",
        "se": "Northern Sami",
        "sei": "Seri",
        "sgs": "Samogitian",
        "shn": "Shan",
        "sid": "Sidamo",
        "sm": "Samoan",
        "sma": "Southern Sami",
        "smj": "Lule Sami",
        "smn": "Inari Sami",
        "sms": "Skolt Sami",
        "sn": "Shona",
        "srn": "Sranan Tongo",
        "ss": "Swati",
        "st": "Sesotho",
        "stq": "Saterland Frisian",
        "su": "Sundanese",
        "sux": "Sumerian",
        "sw": "Swahili",
        "szl": "Silesian",
        "tet": "Tetum",
        "tcy": "Tulu",
        "ti": "Tigrinya",
        "tpi": "Tok Pisin",
        "ts": "Tsonga",
        "tt": "Tatar",
        "tum": "Tumbuka",
        "tw": "Twi",
        "ty": "Tahitian",
        "tyv": "Tuvan",
        "udm": "Udmurt",
        "ug": "Uyghur",
        "umb": "Umbundu",
        "vec": "Venetian",
        "vep": "Veps",
        "vls": "West Flemish",
        "vmf": "Main-Franconian",
        "vo": "Volapük",
        "vot": "Votic",
        "vro": "Võro",
        "wa": "Walloon",
        "wae": "Walser",
        "wal": "Wolaytta",
        "war": "Waray",
        "wuu": "Wu Chinese",
        "xal": "Kalmyk",
        "xmf": "Mingrelian",
        "yao": "Yao",
        "yap": "Yapese",
        "yav": "Yangben",
        "ybb": "Yemba",
        "yi": "Yiddish",
        "yo": "Yoruba",
        "yrl": "Nheengatu",
        "yue": "Cantonese",
        "za": "Zhuang",
        "zea": "Zeelandic",
        "zgh": "Standard Moroccan Tamazight",
        "zu": "Zulu"
    },
    "max_file_size_mb": 10,
    "supported_file_types": [".csv", ".xlsx", ".xls"],
    "output_dir": "output",
    "temp_dir": "temp"
}

# Create necessary directories
os.makedirs(DEFAULT_CONFIG["output_dir"], exist_ok=True)
os.makedirs(DEFAULT_CONFIG["temp_dir"], exist_ok=True)

def get_supported_languages() -> Dict[str, str]:
    """Return dictionary of supported language codes and names."""
    return DEFAULT_CONFIG["supported_languages"]

def get_supported_file_types() -> List[str]:
    """Return list of supported file extensions."""
    return DEFAULT_CONFIG["supported_file_types"]

def get_model_config() -> Dict:
    """Return model configuration."""
    return {
        "model": DEFAULT_CONFIG["model"],
        "available_models": DEFAULT_CONFIG["available_models"],
        "batch_size": DEFAULT_CONFIG["batch_size"],
        "rate_limit": DEFAULT_CONFIG["rate_limit"],
        "max_retries": DEFAULT_CONFIG["max_retries"]
    } 